### ISSUE TITLE
Load Testing

### ISSUE THREAD

**Issue by ditpfletcher** [aspnet/Proxy#32]
Started performance loading this library in the last few days and I ran into an issue where I could only get it to perform around 3.3 requests per second.

Had to add System.Net.ServicePointManager.DefaultConnectionLimit = 1000; to my app startup to fix this issue.

**Comment by cbird** [comment]
I think you can achieve the same by providing that in the ProxyOptions, i.e:
`app.RunProxy(new ProxyOptions
{
    Scheme = "https",
    Host = "example.com",
    Port = 443,
    BackChannelMessageHandler = new HttpClientHandler { MaxConnectionsPerServer = 1000 }
});`

**Comment by ditpfletcher** [comment]
Interesting, thanks for your input.  We've ran all out tests etc via the my suggested fix above but if I have time I'll check it out.  Hopefully it helps someone else.
