### ISSUE TITLE
Adding additional Headers?

### ISSUE THREAD

**Issue by dorlandode** [aspnet/Proxy#35]
What do you think about adding the ability to add additional headers to the proxy request.  For example, Authorization: Basic SomeBase64String

I was thinking of adding Headers as an IDictionary<string, string> property on the ProxyOptions.

Then in the ProxyMiddleware adding this on line 84:
            // Add additional headers
            foreach(var header in _options.Headers){
                 if (!requestMessage.Headers.TryAddWithoutValidation(header.Key, header.Value) && requestMessage.Content != null)
                {
                    requestMessage.Content?.Headers.TryAddWithoutValidation(header.Key, header.Value);
                }
            }

**Comment by Tratcher** [comment]
Or even more generic, a `Func<HttpRequestMessage, Task>` that let you customize the request prior to sending it. Something similar for the response as well.

That said, you can do this today if you set the ProxyOptions.BackChannelMessageHandler to something that tweaks the headers.

**Comment by mkosieradzki** [comment]
I would like to grab it and handle together with #10

**Comment by levitatejay** [comment]
@Tratcher 

> That said, you can do this today if you set the ProxyOptions.BackChannelMessageHandler to something that tweaks the headers.

Are you able to provide an example on how to use the BackChannelMessageHandler to modify the request headers and/or content? I've been trying for awhile now and can't get anything working.

**Comment by Tratcher** [comment]
Here are some examples of what you can do in a handler:
https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/http-message-handlers

In these cases you just need to set the final handler to an instance of HttpClientHandler or WebRequestHandler to actually send the request.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2499
