### ISSUE TITLE
NETStandard as global dependency

### ISSUE THREAD

**Issue by mrapan** [aspnet/Proxy#36]
It looks like NETStandard.Library is a global dependency in project.json, this leads to .NET Core dependencies even if targeting full framework.

**Comment by cwe1ss** [comment]
See https://docs.microsoft.com/en-us/dotnet/articles/standard/library

NETStandard.Library is a meta-package. The full framework will use its own libraries.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2498
