### ISSUE TITLE
Support for proxying to path in a (virtual) folder

### ISSUE THREAD

**Issue by RaYell** [aspnet/Proxy#37]
Imagine you want to have the proxy done in such a way that
`example1.com/my/method` is proxied to `example2.com/some/folder/my/method`. The current implementation does not support this case as the resource path is always taken from the original request.

This could be achieved by having additional parameter in `ProxyOptions` and adding this parameter's value to the proxied request URL.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2497
