### ISSUE TITLE
referenced nuget packages do not exist

### ISSUE THREAD

**Issue by freerider7777** [aspnet/Proxy#48]
Microsoft.AspNetCore.Proxy.Samples.csproj references nonexisting packages (1.2.0-*)

**Comment by mkosieradzki** [comment]
You can find those packages in nuget repo https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json .

**Comment by muratg** [comment]
Yep, the packages should be up on myget.  I'd prefer `aspnetcore-dev` feed instead of `aspnetcore-ci-dev` feed though because latter is used mainly by the CI system.

Proxy is not yet ready to ship to nuget.org so these packages are not supported and we don't recommend using it in production.
