### ISSUE TITLE
Question: Is there a way to change url?

### ISSUE THREAD

**Issue by GabrielMancik** [aspnet/Proxy#69]
I can modify host, scheme or port via ProxyOptions. Can I modify also url?

I want url http://localhost:5000/Api/Controller/Id to be proxied to http://localhost:5001/Controller/Id.

Currently I have:
```
app.Map(@"/Api", builder => builder.RunProxy(new ProxyOptions
{
	Scheme = "http",
	Host = "localhost",
	Port = "5001"
}));
```

**Comment by mkosieradzki** [comment]
It was added in #46

**Comment by GabrielMancik** [comment]
Thanks. this issue can be closed.
