### ISSUE TITLE
Dynamically and conditionally selecting target url

### ISSUE THREAD

**Issue by hikalkan** [aspnet/Proxy#70]
Think that I'm creating an application;

* Forwards /api/service1/... -> https://domain1.com/api/service1/...
* Forwards /api/service2/... -> https://domain1.com/api/service2/...

And does nothing (does not forward) for other URLs (example: /api/service3).

Thus, we can forward some URLs but also use MVC framework to provide other services in our application.

So, we need to a configuration option: a mapping or URLs

**Comment by mkosieradzki** [comment]
Duplicate to #10 (and already commited as #46)

**Comment by cosmanovich** [comment]
@mkosieradzki  Is there a nuget package available yet, that contains these changes?

**Comment by mkosieradzki** [comment]
Not to my knowledge. @mikaelm12 , @davidfowl any changes for some preview release?

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2490
