### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Proxy#77]
Please provide more samples on how to use the Proxy middleware; dynamic routing and/or selective routing of URIs to backend services etc.

**Comment by mkosieradzki** [comment]
@grahamehorner I strongly agree. I will try to add some samples in my free time to avoid further confusion.

**Comment by grahamehorner** [comment]
much appreciated; looking around the middleware trying to figure out how to use it; with a few examples I would be happy to document this; looks cool BTW 👍

**Comment by mkosieradzki** [comment]
For dynamic routing please see HttpContext.ProxyRequest extension method. Added in #46

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2487
