### ISSUE TITLE
metrics

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Proxy#78]
Please consider adding some middleware logging/metrics to determine perform and/or any issues with routing to services

**Comment by mkosieradzki** [comment]
Do you have any specific preferences for the underlying mechanism? 

Do you think that some kind of Application Insights integration is a good idea or should we use a different more generic mechanism?

Maybe should we use some basic logging instead?

**Comment by grahamehorner** [comment]
Application Insights would be a nice addition; however I feel that it should be a pluggable logging/metric component; maybe something similar to the kestrel event tracing using EventSource given that the middleware maybe deployed on premise and could possibly log private/confidential information

**Comment by mkosieradzki** [comment]
If you have some ideas for logging implementation, I think it can make a valuable contribution to this project. It would be really great, if you could create a PR.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2486
