### ISSUE TITLE
Install through Nuget

### ISSUE THREAD

**Issue by jnapier** [aspnet/Proxy#80]
I cannot find this package through Nuget. The only available version I see is 0.2.0 from Nov 15, 2016.  I am looking at the Microsoft.AspNetCore.Proxy package. Is this project under a different name? Can spmeone help me on locating the most recent version? Thank you.

**Comment by anorborg** [comment]
I'm also curious about this. It seems 0.3.0 has a decent amount of changes (including some used in the samples, i.e. `IServiceCollection` extensions). I see a reference to rtm in the myget for aspnetcore-dev thats a few months old. Maybe just not published to nuget? https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.AspNetCore.Proxy

**Comment by stijnvanbossuyt** [comment]
How to install 0.3.0 than?

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2484
