### ISSUE TITLE
CORS for CrossDomain is not working

### ISSUE THREAD

**Issue by skkanagaraj** [aspnet/Proxy#95]
OPTIONS https://xyz.co.uk/front/api/Eze/GetEcPrt?_=1528800677059 401 (Unauthorized)

1. Automatically Converts 'Get' to 'Option' request.
2. Failed to load.  https://xyz.co.uk/front/api/Eze/GetEcPrt?_=1528800677059: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://liontrust.sharepoint.com' is therefore not allowed access. The response had HTTP status code 401.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Home#3308
